apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-devops-coda-run-tls
spec:
  secretName: k8s-devops-coda-run
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: k8s.devops.coda.run
  dnsNames:
    - k8s.devops.coda.run
    # - www.k8s.devops.code.run
